### ISSUE TITLE
it comes some small mistakes.

### ISSUE THREAD

**Issue by jason156** [JoneXiong/oejia_menu#3]
could not get cotent for  /oejia_menu/static/src/less/variables.less  defined in dundle 'web.assets.backend'
could not get cotent for  /oejia_menu/static/src/less/navbar.less  defined in dundle 'web.assets.backend'
could not get cotent for  /oejia_menu/static/src/less/style.less  defined in dundle 'web.assets.backend'

I have installed npm, less, less-plugin-clean-css already.

Could you help to check what's reason ? tks in advance.

**Comment by JoneXiong** [comment]
master branch for Odoo 10 and 11, 12.0 branch for odoo 12. please check the branch you are using @jason156
