### ISSUE TITLE
odoo12安装oejia_menu报错

### ISSUE THREAD

**Issue by zhujia1234** [JoneXiong/oejia_menu#5]
新手上路，请求帮助：
odoo12安装这个应用时一直报错，报错信息如下
![image](https://user-images.githubusercontent.com/32842651/53612296-bb3b2380-3c0c-11e9-921c-53f9b61890b3.png)

**Comment by zhujia1234** [comment]
已解决

**Comment by gyx465279680** [comment]
12版本，安装报错，一些继承web的视图ID找不到，麻烦大神，帮忙指导下。。

**Comment by JoneXiong** [comment]
@gyx465279680 创建新的issue吧，把你的odoo版本和环境说明下，包括报错信息也截图发出来，这样我们才能去分析嘛
