### ISSUE TITLE
odoo

### ISSUE THREAD

**Issue by gyx465279680** [JoneXiong/oejia_menu#6]

**Comment by gyx465279680** [comment]
您好：odoo12 版本安装报错，麻烦您帮忙解决一下。
报错信息：
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not get content for /oejia_menu/static/src/less/variables.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/style.less defined in bundle 'web.assets_backend'.
Could not execute command 'lessc'This error occured while compiling the bundle 'web.assets_backend' containing:
- /web/static/lib/bootstrap/scss/_functions.scss
- /web/static/lib/bootstrap/scss/_mixins.scss
- /web/static/src/scss/utils.scss
- /web/static/src/scss/bs_mixins_overrides.scss
- /web/static/src/scss/primary_variables.scss
- /web_editor/static/src/scss/web_editor.variables.scss
- /web/static/src/scss/secondary_variables.scss
- /web/static/src/scss/bootstrap_overridden.scss
- /web_editor/static/src/scss/bootstrap_overridden.scss
- /web/static/src/scss/import_bootstrap_part1.scss
- /web/static/src/scss/bs_mixins_overrides.scss
- /web/static/src/scss/import_bootstrap_part2.scss
- /web/static/src/scss/bootstrap_review.scss
- /web/static/src/scss/webclient_extra.scss
- /web/static/src/scss/webclient_layout.scss
- /web/static/src/scss/webclient.scss
- /web/static/src/scss/domain_selector.scss
- /web/static/src/scss/model_field_selector.scss
- /web/static/src/scss/progress_bar.scss
- /web/static/src/scss/dropdown.scss
- /web/static/src/scss/dropdown_extra.scss
- /web/static/src/scss/tooltip.scss
- /web/static/src/scss/debug_manager.scss
- /web/static/src/scss/control_panel.scss
- /web/static/src/scss/fields.scss
- /web/static/src/scss/fields_extra.scss
- /web/static/src/scss/views.scss
- /web/static/src/scss/pivot_view.scss
- /web/static/src/scss/graph_view.scss
- /web/static/src/scss/form_view.scss
- /web/static/src/scss/form_view_extra.scss
- /web/static/src/scss/list_view.scss
- /web/static/src/scss/list_view_extra.scss
- /web/static/src/scss/kanban_dashboard.scss
- /web/static/src/scss/kanban_examples_dialog.scss
- /web/static/src/scss/kanban_column_progressbar.scss
- /web/static/src/scss/kanban_view.scss
- /web/static/src/scss/kanban_view_mobile.scss
- /web/static/src/scss/web_calendar.scss
- /web/static/src/scss/search_view.scss
- /web/static/src/scss/search_view_mobile.scss
- /web/static/src/scss/dropdown_menu.scss
- /web/static/src/scss/search_view_extra.scss
- /web/static/src/scss/data_export.scss
- /base/static/src/scss/onboarding.scss
- /web/static/src/scss/base_settings.scss
- /web/static/src/scss/report_backend.scss
- /base_import/static/src/scss/base_import.scss
- /web_diagram/static/src/scss/diagram_view.scss
- /web_editor/static/src/scss/web_editor.common.scss
- /web_editor/static/src/scss/web_editor.backend.scss
- /oejia_menu/static/src/less/variables.less
- /oejia_menu/static/src/less/navbar.less
- /oejia_menu/static/src/less/style.less
- /web_settings_dashboard/static/src/scss/dashboard.scss
Could not get content for /oejia_menu/static/src/less/variables.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/style.less defined in bundle 'web.assets_backend'.

**Comment by JoneXiong** [comment]
重复的问题
