### ISSUE TITLE
odoo12 社区版本安装报错

### ISSUE THREAD

**Issue by gyx465279680** [JoneXiong/oejia_menu#7]
您好：odoo12 版本安装报错，麻烦您帮忙解决一下。
报错信息：
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not get content for /oejia_menu/static/src/less/variables.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/style.less defined in bundle 'web.assets_backend'.
Could not execute command 'lessc'This error occured while compiling the bundle 'web.assets_backend' containing:
- /web/static/lib/bootstrap/scss/_functions.scss
- /web/static/lib/bootstrap/scss/_mixins.scss
- /web/static/src/scss/utils.scss
- /web/static/src/scss/bs_mixins_overrides.scss
- /web/static/src/scss/primary_variables.scss
- /web_editor/static/src/scss/web_editor.variables.scss
- /web/static/src/scss/secondary_variables.scss
- /web/static/src/scss/bootstrap_overridden.scss
- /web_editor/static/src/scss/bootstrap_overridden.scss
- /web/static/src/scss/import_bootstrap_part1.scss
- /web/static/src/scss/bs_mixins_overrides.scss
- /web/static/src/scss/import_bootstrap_part2.scss
- /web/static/src/scss/bootstrap_review.scss
- /web/static/src/scss/webclient_extra.scss
- /web/static/src/scss/webclient_layout.scss
- /web/static/src/scss/webclient.scss
- /web/static/src/scss/domain_selector.scss
- /web/static/src/scss/model_field_selector.scss
- /web/static/src/scss/progress_bar.scss
- /web/static/src/scss/dropdown.scss
- /web/static/src/scss/dropdown_extra.scss
- /web/static/src/scss/tooltip.scss
- /web/static/src/scss/debug_manager.scss
- /web/static/src/scss/control_panel.scss
- /web/static/src/scss/fields.scss
- /web/static/src/scss/fields_extra.scss
- /web/static/src/scss/views.scss
- /web/static/src/scss/pivot_view.scss
- /web/static/src/scss/graph_view.scss
- /web/static/src/scss/form_view.scss
- /web/static/src/scss/form_view_extra.scss
- /web/static/src/scss/list_view.scss
- /web/static/src/scss/list_view_extra.scss
- /web/static/src/scss/kanban_dashboard.scss
- /web/static/src/scss/kanban_examples_dialog.scss
- /web/static/src/scss/kanban_column_progressbar.scss
- /web/static/src/scss/kanban_view.scss
- /web/static/src/scss/kanban_view_mobile.scss
- /web/static/src/scss/web_calendar.scss
- /web/static/src/scss/search_view.scss
- /web/static/src/scss/search_view_mobile.scss
- /web/static/src/scss/dropdown_menu.scss
- /web/static/src/scss/search_view_extra.scss
- /web/static/src/scss/data_export.scss
- /base/static/src/scss/onboarding.scss
- /web/static/src/scss/base_settings.scss
- /web/static/src/scss/report_backend.scss
- /base_import/static/src/scss/base_import.scss
- /web_diagram/static/src/scss/diagram_view.scss
- /web_editor/static/src/scss/web_editor.common.scss
- /web_editor/static/src/scss/web_editor.backend.scss
- /oejia_menu/static/src/less/variables.less
- /oejia_menu/static/src/less/navbar.less
- /oejia_menu/static/src/less/style.less
- /web_settings_dashboard/static/src/scss/dashboard.scss
Could not get content for /oejia_menu/static/src/less/variables.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/navbar.less defined in bundle 'web.assets_backend'.
Could not get content for /oejia_menu/static/src/less/style.less defined in bundle 'web.assets_backend'.

**Comment by JoneXiong** [comment]
确认下模块文件夹名是否为 oejia_menu

**Comment by gyx465279680** [comment]
是的， 原是Oejia_menu ， 改成小写的o  还是报错；麻烦您了，帮忙解决指导一下

**Comment by gyx465279680** [comment]
还是报上面的错误信息

**Comment by JoneXiong** [comment]
应该是odoo运行环境没有装lessc导致无法编译less文件，安装即可。如果安装后仍然无法检测到可自行把less路径写上去 

![image](https://user-images.githubusercontent.com/2276625/67010615-92768880-f120-11e9-8ac1-8b126ffe0c8e.png)

**Comment by gyx465279680** [comment]
谢谢， 会出odoo13版本的吗？什么时间出？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JoneXiong"<notifications@github.com&gt;; 
发送时间: 2019年10月17日(星期四) 晚上8:57
收件人: "JoneXiong/oejia_menu"<oejia_menu@noreply.github.com&gt;; 
抄送: "宫彦鑫"<465279680@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JoneXiong/oejia_menu] odoo12 社区版本安装报错 (#7)




应该是odoo运行环境没有装lessc导致无法编译less文件，安装即可。如果安装后仍然无法检测到可自行把less路径写上去
